# Generated by Django 3.2 on 2021-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact',
        ),
    ]
